title: "The Sleuth Kit Wiki"
description: "Knowledge base for The Sleuth Kit and Autopsy digital forensics tools"
baseurl: ""
url: "https://wiki.sleuthkit.org"

markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - convert.py
  - "*.xml"
  - Gemfile
  - Gemfile.lock
  - vendor/
